services:
  web:
    image: jitsi/web:stable
    restart: unless-stopped
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ./config/web:/config # Ruta relativa
    env_file: .env
    networks:
      meet.jitsi:

  prosody:
    image: jitsi/prosody:stable
    restart: unless-stopped
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ./config/prosody:/config # Ruta relativa
    env_file: .env
    environment:
      - ENABLE_RECORDING=1
    networks:
      meet.jitsi:
        aliases:
          - ${XMPP_SERVER}
          - ${XMPP_DOMAIN}
          - xmpp.meet.jitsi
          - ${XMPP_RECORDER_DOMAIN}

  jicofo:
    image: jitsi/jicofo:stable
    restart: unless-stopped
    volumes:
      - ./config/jicofo:/config
    env_file: .env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jvb:
    image: jitsi/jvb:stable
    restart: unless-stopped
    ports:
      - '10000:10000/udp'
      - '3478:3478/udp'
    volumes:
      - ./config/jvb:/config
    env_file: .env
    depends_on:
      - prosody
    networks:
      meet.jitsi:

  jibri:
    image: jitsi/jibri:stable
    restart: unless-stopped
    shm_size: '2gb'
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ./config/jibri:/config
    env_file: .env
    environment:
      - DISPLAY=:0
      - JIBRI_SKIP_ALSA_CHECK=1
      # Usamos la variable del .env correctamente
      - JIBRI_CHROMIUM_FLAGS=${JIBRI_CHROMIUM_FLAGS}
      - JIBRI_ENTRY_URL_PARAMETERS=#config.filmStripOnly=true&config.hideConferenceTimer=true&interfaceConfig.TOOLBAR_BUTTONS=[]
    extra_hosts:
      - "${LETSENCRYPT_DOMAIN}:host-gateway"
    depends_on:
      - prosody
    networks:
      meet.jitsi:

networks:
  meet.jitsi: