

#LOG_FILE="/config/acme.sh/acme.sh.log"
#LOG_LEVEL=1

#AUTO_UPGRADE="1"

#NO_TIMESTAMP=1

    
ACCOUNT_EMAIL='juanskate326@gmail.com'
UPGRADE_HASH='347cc207cd34ae96b38aca19ceb3b72febb86c9f'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
