CA_EMAIL='juanskate326@gmail.com'
CA_EAB_KEY_ID='GMPBQ9GvlrJ0HaGP8zQ2Aw'
CA_EAB_HMAC_KEY='6SI5dx_JLcuJmx_eEnqq6GkciRd2mKyPbFutsDPI6Z6Ms4eLx4Sj6Zfc0AUHlwJd-jRDzxQ5VY14hx7MpTulDg'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/GMPBQ9GvlrJ0HaGP8zQ2Aw'
CA_KEY_HASH='zagAY379QtuhBRwJlfgWRABmlwGDNnRLY+IOQRh9IsQ='
